// Generated by CoffeeScript 1.10.0
(function() {
  var register;

  register = function() {
    var $confirmPssField, $email_field, $password_field, confirmPass, email, emailRegex, password, passwordRegex;
    $email_field = $('[name="email-register"]');
    email = $email_field.val();
    emailRegex = /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/;
    if (!emailRegex.test(email)) {
      $email_field.addClass('input-error');
      $('.email-error').removeClass('hidden');
      return;
    }
    $email_field.removeClass('input-error');
    $('.email-error').addClass('hidden');
    $password_field = $('[name="password-register"]');
    password = $password_field.val();
    passwordRegex = /^(?=.*[a-z])[0-9a-zA-Z]{8,}$/;
    if (!passwordRegex.test(password)) {
      $password_field.addClass('input-error');
      $('.password-register-error').removeClass('hidden');
      return;
    }
    $password_field.removeClass('input-error');
    $('.password-register-error').addClass('hidden');
    $confirmPssField = $('[name="confirm-password"]');
    confirmPass = $confirmPssField.val();
    if (password !== confirmPass) {
      $confirmPssField.addClass('input-error');
      $('.confirm-password-error').removeClass('hidden');
      return;
    }
    $confirmPssField.removeClass('input-error');
    $('.confirm-password-error').addClass('hidden');
    $.post('/register', {
      email: email,
      password: password
    }, function(json) {
      var error;
      if (json.success) {
        $('.defined-error').addClass('hidden');
        window.location.href = "/";
      } else {
        error = $('.defined-error');
        error.html(json.message);
        error.removeClass('hidden');
      }
    });
    return;
  };

  $(function() {
    $('#login-form-link').click(function(e) {
      $('#register-form').addClass('hidden');
      $('#login-form').delay(100).fadeIn(100);
      $('#register-form').fadeOut(100);
      $('#register-form-link').removeClass('active');
      $(this).addClass('active');
      e.preventDefault();
    });
    $('#register-form-link').click(function(e) {
      $('#register-form').removeClass('hidden');
      $('#register-form').delay(100).fadeIn(100);
      $('#login-form').fadeOut(100);
      $('#login-form-link').removeClass('active');
      $(this).addClass('active');
      e.preventDefault();
    });
    $('#register-submit').click(function(e) {
      register();
    });
    $('[name="login-submit"]').click(function(e) {
      var $email_field, $password_field, email, emailRegex, password, passwordRegex;
      $email_field = $('[name="username"]');
      email = $email_field.val();
      emailRegex = /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/;
      if (!emailRegex.test(email)) {
        $email_field.addClass('input-error');
        $('.username-error').removeClass('hidden');
        return;
      }
      $email_field.removeClass('input-error');
      $('.username-error').addClass('hidden');
      $password_field = $('[name="password"]');
      password = $password_field.val();
      passwordRegex = /^(?=.*[a-z])[0-9a-zA-Z]{8,}$/;
      if (!passwordRegex.test(password)) {
        $password_field.addClass('input-error');
        $('.password-error').removeClass('hidden');
        return;
      }
      $.post('/doLogin', {
        email: email,
        password: password
      }, function(json) {
        var error;
        if (json.success) {
          $('.defined-error').addClass('hidden');
          window.location.href = "/home";
        } else {
          error = $('.defined-error');
          error.html(json.message);
          error.removeClass('hidden');
        }
      });
    });
    $(document).keypress(function(e) {
      if (e.which === 13) {
        if ($('#register-form-link').hasClass('active')) {
          register();
        }
      }
    });
  });

}).call(this);
